/*
ALL ALARMS
*/
GET https://l9enkvivp3.execute-api.us-east-1.amazonaws.com/testing/alarms

HTTP/1.1 200  - OK
date: Tue, 05 Dec 2023 09:21:36 GMT
content-type: application/json
content-length: 50
connection: close
x-amzn-requestid: 4594296d-cb1d-445a-88dd-be1e4687c2b3
x-amz-apigw-id: PdnA6E_AoAMEa9g=
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-amzn-trace-id: Root=1-656eeb9f-33de18044375939619fd04c3;Sampled=0;lineage=ed58f588:0
###
GET https://l9enkvivp3.execute-api.us-east-1.amazonaws.com/testing/updateallstock

HTTP/1.1 200  - OK
date: Thu, 07 Dec 2023 09:23:02 GMT
content-type: text/plain; charset=UTF-8
content-length: 43
connection: close
x-amzn-requestid: 926c99d8-f2c0-40c4-9e71-74c36d1002aa
x-amzn-remapped-content-length: 43
x-amz-apigw-id: PkNE7G9ZoAMEEiQ=
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-amzn-trace-id: Root=1-65718eec-5ed712c935b0f003081635a8;Sampled=0;lineage=ed58f588:0
###
GET https://l9enkvivp3.execute-api.us-east-1.amazonaws.com/testing/highbuy

HTTP/1.1 200  - OK
date: Fri, 01 Dec 2023 10:45:40 GMT
content-type: application/json
content-length: 934
connection: close
x-amzn-requestid: 7a9777b6-19ae-404d-95fe-1e7f8e42e33f
x-amz-apigw-id: PQnkeGI-oAMEcNg=
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-amzn-trace-id: Root=1-6569b94f-1ca2c71f5525ca2f13e6651b;Sampled=0;lineage=ed58f588:0
###
GET https://l9enkvivp3.execute-api.us-east-1.amazonaws.com/testing/allrsi

HTTP/1.1 404  - Not Found
date: Fri, 01 Dec 2023 10:46:00 GMT
content-type: application/json
content-length: 0
connection: close
x-amzn-requestid: a64d71f7-d398-4726-98dd-9faa265b6bc8
x-amz-apigw-id: PQnnRGHPIAMErXQ=
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-amzn-trace-id: Root=1-6569b961-1ce41ad77d002e617e590454;Sampled=0;lineage=5537306b:0
###
GET https://l9enkvivp3.execute-api.us-east-1.amazonaws.com/testing/crossrsi

HTTP/1.1 200  - OK
date: Fri, 01 Dec 2023 10:46:08 GMT
content-type: application/json
content-length: 2380
connection: close
x-amzn-requestid: 73611797-6314-4739-a0a4-375507b9c18b
x-amz-apigw-id: PQnpdEHtoAMEFKA=
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-amzn-trace-id: Root=1-6569b96f-05e039b72a773be978103eab;Sampled=0;lineage=ed58f588:0
###
GET https://l9enkvivp3.execute-api.us-east-1.amazonaws.com/testing/allha

HTTP/1.1 200  - OK
date: Tue, 05 Dec 2023 08:24:18 GMT
content-type: application/json
content-length: 303
connection: close
x-amzn-requestid: 0691c6bf-1630-4168-926c-73900d9ac95a
x-amz-apigw-id: PdenpGEBoAMENxA=
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-amzn-trace-id: Root=1-656ede30-048d623f7efc07150e6eec72;Sampled=0;lineage=ed58f588:0
###
GET https://khfdw071s5.execute-api.us-east-1.amazonaws.com/testing/allstocks

HTTP/1.1 200  - OK
date: Fri, 01 Dec 2023 10:19:21 GMT
content-type: application/json
content-length: 18576
connection: close
x-amzn-requestid: 785c5ad8-00a1-488d-9817-4cc42ca80907
x-amz-apigw-id: PQjujGHwIAMEkbA=
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-amzn-trace-id: Root=1-6569b329-4a1f92551a37d61465f9a638;Sampled=0;lineage=5537306b:0
###
GET https://khfdw071s5.execute-api.us-east-1.amazonaws.com/testing/refresh

HTTP/1.1 200  - OK
date: Wed, 06 Dec 2023 19:16:29 GMT
content-type: application/json
content-length: 10
connection: close
x-amzn-requestid: 4993f327-69e8-4a90-ac03-ff7d44fe5cef
x-amz-apigw-id: PiRDpGW6oAMEIqQ=
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-amzn-trace-id: Root=1-6570c87d-46df1bfd391f122f639ce2bd;Sampled=0;lineage=5537306b:0
###
GET https://75pvdklpi4.execute-api.us-east-1.amazonaws.com/default/firstpython

HTTP/1.1 200  - OK
date: Thu, 07 Dec 2023 09:36:18 GMT
content-type: text/plain; charset=utf-8
content-length: 20
connection: close
apigw-requestid: PkPCOgb1oAMEJ2A=